global sim_dir oper_dir iter_dir conc_dir adj_dir ... 
       iter_label conc_label adj_label grad_label ...
       H save_flag t reg_par B_inv nPass max_iters space_int_wgt ...
       s_star m_star c_star s_b x_0 f_0 g_0 g_proj_0 c...
       lb ub nbd